name: trenchripper
channels:
  - conda-forge
  - pyviz
dependencies:
  - python>=3.10
  - bokeh
  - dask=2025.10.0
  - dask-jobqueue
  - dask-ml
  - datashader
  - distributed=2025.10.0
  - h5py
  - holoviews
  - ipympl
  - ipywidgets
  - jupyterlab
  - line_profiler
  - matplotlib
  - nd2reader
  - nodejs
  - numpy
  - pandas
  - pip
  - pyarrow>=10.0.0
  - pytables
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tifffile
  - zarr
  - pip:
      - pulp
      - parse
